/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp._javaandwebsetprojects._6__java_220and_220internetmarket;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.util.*;

public class _javaandinternetmarket_0orderform__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=GB2312");
    request.setCharacterEncoding("GB2312");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
							try
							{
								Class.forName("com.mysql.jdbc.Driver");
								Connection Connection1=DriverManager.getConnection("jdbc:mysql://localhost:3306/InternetMarket","root","11235813");
								String[] MerchandiseIDs=request.getParameterValues("CheckBoxes");
								if(session.getAttribute("CustomerID")==null)response.sendRedirect("JavaAndInternetMarket_Customer_LogOn.jsp");
								int CustomerID=(Integer)session.getAttribute("CustomerID");
								String StructuredQueryLanguage="Select  Name From Customer Where CustomerID="+CustomerID;
								ResultSet ResultSet1=Connection1.createStatement().executeQuery(StructuredQueryLanguage);
								ResultSet1.next();
								String CustomerName=ResultSet1.getString("Name");
								GregorianCalendar GregorianCalendar1=new GregorianCalendar();
								String date=GregorianCalendar1.get(Calendar.YEAR)+"-"+(GregorianCalendar1.get(Calendar.MONTH)+1)+"-"+GregorianCalendar1.get(Calendar.DAY_OF_MONTH);
								float FinalPrice=0.0f;
								if(MerchandiseIDs!=null)
								{
									for(int i=0;i<MerchandiseIDs.length;i++)
									{
										StructuredQueryLanguage="Select  * From Merchandise Where MerchandiseID="+MerchandiseIDs[i];
										ResultSet1=Connection1.createStatement().executeQuery(StructuredQueryLanguage);
										ResultSet1.next();
										String MerchandiseName=ResultSet1.getString("Name");
										int MerchandiseSum=Integer.parseInt(request.getParameter("Text"+MerchandiseIDs[i]));
										int Stocks=ResultSet1.getInt("Stocks");
										if(MerchandiseSum>Stocks)MerchandiseSum=Stocks;
										StructuredQueryLanguage="Update Merchandise Set Stocks="+(Stocks-MerchandiseSum)+" Where MerchandiseID="+MerchandiseIDs[i];
										Connection1.createStatement().executeUpdate(StructuredQueryLanguage);
										float MerchandisePrice=ResultSet1.getFloat("Price");
										FinalPrice+=MerchandiseSum*MerchandisePrice;
										StructuredQueryLanguage="Insert Into OrderForm (CustomerID,MerchandiseID,Sum,Date) Values ("+CustomerID+","+MerchandiseIDs[i]+","+MerchandiseSum+",'"+date+"')";
										Connection1.createStatement().executeUpdate(StructuredQueryLanguage);
										StructuredQueryLanguage="Select Max(OrderFormID) As NewOrderFormID From OrderForm";
										ResultSet1=Connection1.createStatement().executeQuery(StructuredQueryLanguage);
										ResultSet1.next();
										int OrderFormID=ResultSet1.getInt("NewOrderFormID");

						
      out.write(_jsp_string1, 0, _jsp_string1.length);
      out.print((OrderFormID));
      out.write(_jsp_string2, 0, _jsp_string2.length);
      out.print((CustomerID));
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((CustomerName));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((MerchandiseIDs[i]));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((MerchandiseName));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((MerchandiseSum));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((MerchandisePrice));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      
									}
								}
								else
								{
						
      out.write(_jsp_string9, 0, _jsp_string9.length);
      
									
								}
								Connection1.close();
						
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print((date));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print((FinalPrice));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      
							}
							catch(Exception e){out.print(e.toString());}
						
      out.write(_jsp_string13, 0, _jsp_string13.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("JavaAndWebSetProjects/6.Java And InternetMarket/JavaAndInternetMarket_OrderForm.jsp"), -4340879093821172167L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  private final static char []_jsp_string10;
  private final static char []_jsp_string13;
  private final static char []_jsp_string7;
  private final static char []_jsp_string5;
  private final static char []_jsp_string2;
  private final static char []_jsp_string8;
  private final static char []_jsp_string6;
  private final static char []_jsp_string9;
  private final static char []_jsp_string11;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string12;
  static {
    _jsp_string0 = "\r\n\r\n\r\n\r\n<Html>\r\n	<Head>\r\n		<Title>JavaAndInternetMarket_OrderForm</Title>\r\n	</Head>\r\n	<Body Text=597C17 VLink=White ALink=Blue>\r\n		<Form Name=Form1 Action=JavaAndInternetMarket_OrderList.jsp Method=post>\r\n			<Table Align=Center Width=1000 Height=300 BackGround=\"Internet Market\\InternetMarket.jpg\">\r\n				<Image Src=\"Internet Market\\InternetMarket_Head.jpg\"><Br>\r\n				<Tr><Marquee  Behavior=Alternate ScrollAmount=10 BackGround=\"Internet Market\\InternetMarket.jpg\" BGColor=#FFD457><Font Color= 597C17 Size=5 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Welcome to the Internet Market! Have a Good Time!<B></Font></Marquee></Tr><Br>\r\n				<Tr><Td Align=Center>\r\n					<Table Align=Center Width=800  Height=50 Border=1 BorderColor=597C17 BackGround=\"Internet Market\\InternetMarket_OrderForm.jpg\">\r\n						<Tr><Td  Align=Center><Font Color= 597C17 Size=10 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>OrderForms Information :</B></Td></Tr>\r\n						".toCharArray();
    _jsp_string3 = "</B></Td>\r\n														<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Customer Name:".toCharArray();
    _jsp_string10 = "\r\n								<Tr>\r\n									<Td>\r\n										<Table Width=750 Align=Center Border=1 BorderColor=597C17>\r\n											<Tr>\r\n												<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Date:".toCharArray();
    _jsp_string13 = "\r\n					</Table>\r\n				</Td></Tr>\r\n			</Table>		\r\n		</Form>\r\n	</Body>\r\n</Html>".toCharArray();
    _jsp_string7 = "</B></Td>\r\n														<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Merchandise Price:".toCharArray();
    _jsp_string5 = "</B></Td>\r\n														<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Merchandise Name:".toCharArray();
    _jsp_string2 = "</B></Td></Tr>\r\n													<Tr>\r\n														<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>CustomerID:".toCharArray();
    _jsp_string8 = "</B></Td>\r\n													</Tr>\r\n												</Table>\r\n											</Td>\r\n										</Tr>\r\n						".toCharArray();
    _jsp_string6 = "</B></Td>\r\n													</Tr>\r\n													<Tr>\r\n														<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Merchandise Sum:".toCharArray();
    _jsp_string9 = "\r\n									<Tr>\r\n										<Td>\r\n											<Table Width=750 Align=Center Border=1 BorderColor=597C17>\r\n												<Tr><Td><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>You Have Not Choose Any One!</B></Td></Tr>	\r\n											</Table>\r\n										</Td>\r\n									</Tr>\r\n						".toCharArray();
    _jsp_string11 = "</B></Td>\r\n												<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Final Price:".toCharArray();
    _jsp_string4 = "</B></Td>\r\n													</Tr>\r\n													<Tr>\r\n														<Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>MerchandiseID:".toCharArray();
    _jsp_string1 = "\r\n										<Tr>\r\n											<Td>\r\n												<Table Width=750 Align=Center Border=1 BorderColor=597C17>\r\n													<Tr><Td ColSpan=2><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>OrderFormID:".toCharArray();
    _jsp_string12 = "</B></Td>\r\n											</Tr>\r\n										</Table>\r\n									</Td>\r\n								</Tr>\r\n						".toCharArray();
  }
}
