/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp._javaandwebsetprojects._6__java_220and_220internetmarket;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;

public class _javaandinternetmarket_0customer__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=GB2312");
    request.setCharacterEncoding("GB2312");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      
		if(request.getParameter("Text1")==null)response.sendRedirect("JavaAndInternetMarket_Customer_LogOn.jsp");
	
      out.write(_jsp_string1, 0, _jsp_string1.length);
      JavaAndInternetMarket.PasswordProcessor PasswordProcessor1;
      PasswordProcessor1 = (JavaAndInternetMarket.PasswordProcessor) pageContext.getAttribute("PasswordProcessor1");
      if (PasswordProcessor1 == null) {
        PasswordProcessor1 = new JavaAndInternetMarket.PasswordProcessor();
        pageContext.setAttribute("PasswordProcessor1", PasswordProcessor1);
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      
							try
							{
								Class.forName("com.mysql.jdbc.Driver");
								Connection Connection1=DriverManager.getConnection("jdbc:mysql://localhost:3306/InternetMarket","root","11235813");
								String StructuredQueryLanguage="Select  CustomerID From Customer Where Name='"+request.getParameter("Text1")+"'";
								ResultSet ResultSet1=Connection1.createStatement().executeQuery(StructuredQueryLanguage);
								if(!ResultSet1.next())response.sendRedirect("JavaAndInternetMarket_Customer_Register.jsp");
								StructuredQueryLanguage="Select  CustomerID From Customer Where Name='"+request.getParameter("Text1")+"' And Password='"+PasswordProcessor1.getCodeByPassword(request.getParameter("Password1"))+"'";
								ResultSet1=Connection1.createStatement().executeQuery(StructuredQueryLanguage);
								if(!ResultSet1.next())
								{
									out.print("<Tr><Td Align=Center ColSpan=2><Font Color= 597C17 Size=5 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>I am Sorry,Your Password is Wrong! Please Input it Again!</B></Td></Tr>");
									response.setHeader("refresh","4;URL=JavaAndInternetMarket_Customer_LogOn.jsp");
								}
								else session.setAttribute("CustomerID",ResultSet1.getInt("CustomerID"));
								out.print("CustomerID="+session.getAttribute("CustomerID"));
								String[] MerchandiseIDs=request.getParameterValues("Hiddens");
								if(MerchandiseIDs!=null&&(!MerchandiseIDs[0].equals("null")))
								{
									for(int i=0;i<MerchandiseIDs.length;i++)
									{
										StructuredQueryLanguage="Select  * From Merchandise Where MerchandiseID="+MerchandiseIDs[i];
										ResultSet1=Connection1.createStatement().executeQuery(StructuredQueryLanguage);
										while(ResultSet1.next())
										{
						
      out.write(_jsp_string3, 0, _jsp_string3.length);
      out.print((ResultSet1.getString("Name")));
      out.write(_jsp_string4, 0, _jsp_string4.length);
      out.print((ResultSet1.getString("MerchandiseID")));
      out.write(_jsp_string5, 0, _jsp_string5.length);
      out.print((ResultSet1.getString("Name")));
      out.write(_jsp_string6, 0, _jsp_string6.length);
      out.print((ResultSet1.getString("Classification")));
      out.write(_jsp_string7, 0, _jsp_string7.length);
      out.print((ResultSet1.getString("Description")));
      out.write(_jsp_string8, 0, _jsp_string8.length);
      out.print((ResultSet1.getFloat("Price")));
      out.write(_jsp_string9, 0, _jsp_string9.length);
      out.print((ResultSet1.getInt("Stocks")));
      out.write(_jsp_string10, 0, _jsp_string10.length);
      out.print(( ResultSet1.getInt("MerchandiseID")));
      out.write(_jsp_string11, 0, _jsp_string11.length);
      out.print(( ResultSet1.getInt("MerchandiseID")));
      out.write(_jsp_string12, 0, _jsp_string12.length);
      
										}
									}
								}
								else
								{
									StructuredQueryLanguage="Select  * From Merchandise Where Stocks>0";
									ResultSet1=Connection1.createStatement().executeQuery(StructuredQueryLanguage);
									for(int i=0;i<6&&ResultSet1.next();i++)
									{

						
      out.write(_jsp_string13, 0, _jsp_string13.length);
      out.print((ResultSet1.getString("Name")));
      out.write(_jsp_string14, 0, _jsp_string14.length);
      out.print((ResultSet1.getString("MerchandiseID")));
      out.write(_jsp_string15, 0, _jsp_string15.length);
      out.print((ResultSet1.getString("Name")));
      out.write(_jsp_string16, 0, _jsp_string16.length);
      out.print((ResultSet1.getString("Classification")));
      out.write(_jsp_string17, 0, _jsp_string17.length);
      out.print((ResultSet1.getFloat("Price")));
      out.write(_jsp_string18, 0, _jsp_string18.length);
      out.print(( ResultSet1.getInt("MerchandiseID")));
      out.write(_jsp_string19, 0, _jsp_string19.length);
      out.print(( ResultSet1.getInt("MerchandiseID")));
      out.write(_jsp_string20, 0, _jsp_string20.length);
      
									}
								}
								Connection1.close();
							}
							catch(Exception e){out.print(e.toString());}
						
      out.write(_jsp_string21, 0, _jsp_string21.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("JavaAndWebSetProjects/6.Java And InternetMarket/JavaAndInternetMarket_Customer.jsp"), -4638416571084790520L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string18;
  private final static char []_jsp_string21;
  private final static char []_jsp_string7;
  private final static char []_jsp_string17;
  private final static char []_jsp_string1;
  private final static char []_jsp_string8;
  private final static char []_jsp_string11;
  private final static char []_jsp_string15;
  private final static char []_jsp_string20;
  private final static char []_jsp_string16;
  private final static char []_jsp_string2;
  private final static char []_jsp_string13;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  private final static char []_jsp_string10;
  private final static char []_jsp_string3;
  private final static char []_jsp_string4;
  private final static char []_jsp_string0;
  private final static char []_jsp_string19;
  private final static char []_jsp_string12;
  private final static char []_jsp_string14;
  private final static char []_jsp_string9;
  static {
    _jsp_string18 = "</B></Td></Tr>\r\n													<Tr><Td><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>I Want to Buy this:<Input Type=CheckBox Name=CheckBoxes Value=".toCharArray();
    _jsp_string21 = "\r\n						<Tr><Td Align=Center><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Images</B></Td><Td  Align=Center><Input Type=Submit Value=\"I Want To Add All Of Them To My OrderForm !\"><Input Type=Reset Value=\"I Want To Reset All Of The Records !\"></Td></Tr>\r\n					</Table>\r\n				</Form>\r\n			</Td></Tr>\r\n		</Table>		\r\n	</Body>\r\n</Html>".toCharArray();
    _jsp_string7 = "</B></Td></Tr>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Description:".toCharArray();
    _jsp_string17 = "</B></Td></Tr>\r\n													<Tr><Td><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Price:".toCharArray();
    _jsp_string1 = "\r\n	<Body Text=597C17 VLink=White ALink=Blue>\r\n		<Table Align=Center Width=1000 Height=300 BackGround=\"Internet Market\\InternetMarket.jpg\">\r\n			<Image Src=\"Internet Market\\InternetMarket_Head.jpg\"><Br>\r\n			<Tr><Marquee  Behavior=Alternate ScrollAmount=10 BackGround=\"Internet Market\\InternetMarket.jpg\" BGColor=#FFD457><Font Color= 597C17 Size=5 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Welcome to the Internet Market! Have a Good Time!<B></Font></Marquee></Tr><Br>\r\n			<Tr><Td Align=Center>\r\n				<Form Name=Form2 Action=JavaAndInternetMarket_Customer_Query.jsp Method=post>\r\n					<Table Align=Center Width=900  Height=50 Border=1 BorderColor=597C17>\r\n						<Tr>\r\n							<Td Align=Left><Font Color= 597C17 Size=5 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Merchandise Name:</B></Td>\r\n							<Td Align=Center><Input Type=Text Name=Text_Name  Size=70></Td>\r\n							<Td Align=Center><Input Type=Submit Value=Query Name=Submit_Name onClick=fuction1()><Input Type=Reset Value=Reset></Td>\r\n						</Tr>\r\n					</Table>\r\n				</Form>\r\n			</Td></Tr>\r\n			<Tr><Td Align=Center>\r\n				<Form Name=Form1 Action=JavaAndInternetMarket_OrderForm.jsp Method=post>\r\n					<Table Align=Center Width=800  Height=50 Border=1 BorderColor=597C17>\r\n						<Tr><Td  Align=Center ColSpan=4><Font Color= 597C17 Size=10 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Merchandise Informations :</B></Td></Tr>\r\n						".toCharArray();
    _jsp_string8 = "</B></Td></Tr>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Price:".toCharArray();
    _jsp_string11 = "></B></Td></Tr>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>How Many Would You Buy?<Input Type=Text Name=Text".toCharArray();
    _jsp_string15 = "</B></Td></Tr>\r\n													<Tr><Td><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Name:".toCharArray();
    _jsp_string20 = " Value=\"1\"></B></Td></Tr>\r\n												</Table>\r\n											</Td>\r\n										</Tr>\r\n						".toCharArray();
    _jsp_string16 = "</B></Td></Tr>\r\n													<Tr><Td><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Classification:".toCharArray();
    _jsp_string2 = "\r\n						".toCharArray();
    _jsp_string13 = "\r\n										<Tr>\r\n											<Td Align=Center><Image Height=120 Width=120 src=\"Merchandise Images\\".toCharArray();
    _jsp_string5 = "</B></Td></Tr>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Name:".toCharArray();
    _jsp_string6 = "</B></Td></Tr>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Classification:".toCharArray();
    _jsp_string10 = "</B></Td></Tr>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>I Want to Buy this:<Input Type=CheckBox Name=CheckBoxes Value=".toCharArray();
    _jsp_string3 = "\r\n											<Tr>\r\n												<Td Align=Center><Image Height=220 Width=220 src=\"Merchandise Images\\".toCharArray();
    _jsp_string4 = ".jpg\"></Td>\r\n												<Td>\r\n													<Table Width=750 Align=Center Border=1 BorderColor=597C17>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>MerchandiseID:".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<Html>\r\n	<Head>\r\n		<Title>JavaAndInternetMarket_Customer</Title>\r\n	</Head>\r\n	".toCharArray();
    _jsp_string19 = "></B></Td></Tr>\r\n													<Tr><Td><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>How Many Would You Buy?<Input Type=Text Name=Text".toCharArray();
    _jsp_string12 = " Value=\"1\"></B></Td></Tr>\r\n													</Table>\r\n												</Td>\r\n											</Tr>\r\n						".toCharArray();
    _jsp_string14 = ".jpg\"></Td>\r\n											<Td>\r\n												<Table Width=750 Align=Center Border=1 BorderColor=597C17>\r\n													<Tr><Td><Font Color= 597C17 Size=2 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>MerchandiseID:".toCharArray();
    _jsp_string9 = "</B></Td></Tr>\r\n														<Tr><Td><Font Color= 597C17 Size=4 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Stocks:".toCharArray();
  }
}
