/*
 * JSP generated by Resin-3.1.6 (built Sun, 04 May 2008 03:25:50 PDT)
 */

package _jsp._javawebsetprograming._6__java_220and_220internetmarket;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _javaandinternetmarket_0customer_0logon__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = com.caucho.jsp.QJspFactory.allocatePageContext(this, _jsp_application, request, response, null, null, 8192, true, false);
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html;charset=GB2312");
    request.setCharacterEncoding("GB2312");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      com.caucho.jsp.QJspFactory.freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != -7072480922035483583L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("JavaWebSetPrograming/6.Java And InternetMarket/JavaAndInternetMarket_Customer_LogOn.jsp"), 6954035779458569402L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  private final static char []_jsp_string0;
  static {
    _jsp_string0 = "\r\n<Html>\r\n	<Head>\r\n		<Title>JavaAndInternetMarket_Customer_LogOn</Title>\r\n	</Head>\r\n	<Script Language=JavaScript>\r\n		function function1()\r\n		{\r\n			if(Form1.Text1.value==\"\")alert(\"Name Should not be Empty!\");\r\n			else if(Form1.Password1.value==\"\")alert(\"Password Should not be Empty!\");\r\n			else Form1.submit();\r\n		}\r\n	</Script>\r\n	<Body Text=597C17 VLink=White ALink=Blue>\r\n		<Form Name=Form1 Action=JavaAndInternetMarket_Customer.jsp Method=post>\r\n			<Center>\r\n				<Table Align=Center Width=1000 Height=300 BackGround=\"Internet Market\\InternetMarket.jpg\">\r\n					<Image Src=\"Internet Market\\InternetMarket_Head.jpg\"><Br>\r\n					<Tr><Marquee  Behavior=Alternate ScrollAmount=10 BackGround=\"Internet Market\\InternetMarket.jpg\" BGColor=#FFD457><Font Color= 597C17 Size=5 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Welcome to Log On the Internet Market !<B></Font></Marquee></Tr><Br>\r\n					<Tr><Td Align=Center>\r\n						<Table Align=Center Width=500  Height=350 BackGround=\"Internet Market\\InternetMarket_Input.jpg\" Border=1 BorderColor=597C17>\r\n							<Tr>\r\n								<Td Align=Center><Font Color= 597C17 Size=5 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Name:</B></Td>\r\n								<Td Align=Center><Input Type=Text Name=Text1></Td>\r\n							</Tr>\r\n							<Tr>\r\n								<Td Align=Center><Font Color= 597C17 Size=5 Face=\u5fae\u8f6f\u96c5\u9ed1 ><B>Password:</B></Td>\r\n								<Td Align=Center><Input Type=Password Name=Password1></Td>\r\n							</Tr>\r\n							<Tr><Td Align=Center ColSpan=2><Input Type=Button Value=\"   Log On   \" onClick=function1()>          <Input Type=Reset Value=\"   Clear   \"></Td></Tr>\r\n						</Table>\r\n					</Td></Tr>\r\n				</Table>\r\n			</Center>\r\n		</Form>\r\n	</Body>\r\n</Html>".toCharArray();
  }
}
