import java.awt.*;
import com.sun.j3d.utils.geometry.*;
import com.sun.j3d.utils.universe.*;
import com.sun.j3d.utils.behaviors.mouse.*;
import javax.media.j3d.*;
import javax.vecmath.*;
public class JavaAndMaterial
{
	public static void main(String[] args)
	{
		BranchGroup BranchGroup1=new BranchGroup();
		BoundingSphere BoundingSphere1=new BoundingSphere(new Point3d(0,0,0),300);
		Background Background1=new Background(new Color3f(Color.black));
		Background1.setApplicationBounds(BoundingSphere1);
		BranchGroup1.addChild(Background1);
		Color3f color3f=new Color3f(0f,1f,0f);
		Vector3f vector3f=new Vector3f(0f,0f,-1f);
		DirectionalLight DirectionalLight1=new DirectionalLight(color3f,vector3f);
		DirectionalLight1.setInfluencingBounds(BoundingSphere1);
		BranchGroup1.addChild(DirectionalLight1);
		AmbientLight AmbientLight1=new AmbientLight(true,new Color3f(Color.pink));
		AmbientLight1.setInfluencingBounds(BoundingSphere1);
		BranchGroup1.addChild(AmbientLight1);
		PointLight PointLight1=new PointLight(new Color3f(0f,0f,1f),new Point3f(1f,1f,0f),new Point3f(-1f,-1f,0f));
		PointLight1.setInfluencingBounds(BoundingSphere1);
		BranchGroup1.addChild(PointLight1);
		TransformGroup TransformGroup1=new TransformGroup();
		TransformGroup1.setCapability(18);
		TransformGroup1.setCapability(17);
		BranchGroup1.addChild(TransformGroup1);
		MouseRotate MouseRotate1=new MouseRotate(TransformGroup1);
		MouseRotate1.setTransformGroup(TransformGroup1);
		MouseRotate1.setSchedulingBounds(BoundingSphere1);
		BranchGroup1.addChild(MouseRotate1);
		Appearance Appearance2=new Appearance();
		Material Material2=new Material();
		Material2.setAmbientColor(new Color3f(Color.pink));
		Appearance2.setMaterial(Material2);
		Appearance Appearance3=new Appearance();
		Material Material3=new Material();
		Material3.setEmissiveColor(new Color3f(Color.orange));
		Appearance3.setMaterial(Material3);
		Appearance Appearance4=new Appearance();
		Material Material4=new Material();
		Material4.setSpecularColor(new Color3f(Color.green));
		Appearance4.setMaterial(Material4);
		Appearance Appearance5=new Appearance();
		Material Material5=new Material();
		Material5.setDiffuseColor(new Color3f(Color.blue));
		Material5.setShininess(1f);
		Appearance5.setMaterial(Material5);
		Appearance Appearance6=new Appearance();
		Material Material6=new Material();
		Material6.setDiffuseColor(new Color3f(Color.blue));
		Material6.setShininess(10f);
		Appearance6.setMaterial(Material6);
		Appearance Appearance7=new Appearance();
		Material Material7=new Material();
		Material7.setDiffuseColor(new Color3f(Color.blue));
		Material7.setShininess(100f);
		Appearance7.setMaterial(Material7);
		Transform3D transform3D=new Transform3D();
		transform3D.setScale(new Vector3d(0.5f,1f,0.5f));
		transform3D.setTranslation(new Vector3f(-0.5f,0f,0f));
		TransformGroup TransformGroup2=new TransformGroup(transform3D);
		TransformGroup2.addChild(new Sphere(0.2f,Appearance2));
		transform3D=new Transform3D();
		transform3D.setScale(new Vector3d(0.5f,1f,0.5f));
		transform3D.setTranslation(new Vector3f(-0.3f,0f,0f));
		TransformGroup TransformGroup3=new TransformGroup(transform3D);
		TransformGroup3.addChild(new Sphere(0.2f,Appearance3));
		transform3D=new Transform3D();
		transform3D.setScale(new Vector3d(0.5f,1f,0.5f));
		transform3D.setTranslation(new Vector3f(-0.1f,0f,0f));
		TransformGroup TransformGroup4=new TransformGroup(transform3D);
		TransformGroup4.addChild(new Sphere(0.2f,Appearance4));
		transform3D=new Transform3D();
		transform3D.setScale(new Vector3d(0.5f,1f,0.5f));
		transform3D.setTranslation(new Vector3f(0.1f,0f,0f));
		TransformGroup TransformGroup5=new TransformGroup(transform3D);
		TransformGroup5.addChild(new Sphere(0.2f,Appearance5));
		transform3D=new Transform3D();
		transform3D.setScale(new Vector3d(0.5f,1f,0.5f));
		transform3D.setTranslation(new Vector3f(0.3f,0f,0f));
		TransformGroup TransformGroup6=new TransformGroup(transform3D);
		TransformGroup6.addChild(new Sphere(0.2f,Appearance6));
		transform3D=new Transform3D();
		transform3D.setScale(new Vector3d(0.5f,1f,0.5f));
		transform3D.setTranslation(new Vector3f(0.5f,0f,0f));
		TransformGroup TransformGroup7=new TransformGroup(transform3D);
		TransformGroup7.addChild(new Sphere(0.2f,Appearance7));
		TransformGroup1.addChild(TransformGroup2);
		TransformGroup1.addChild(TransformGroup3);
		TransformGroup1.addChild(TransformGroup4);
		TransformGroup1.addChild(TransformGroup5);
		TransformGroup1.addChild(TransformGroup6);
		TransformGroup1.addChild(TransformGroup7);
		BranchGroup1.compile();
		SimpleUniverse SimpleUniverse1=new SimpleUniverse();
		SimpleUniverse1.getViewingPlatform().setNominalViewingTransform();
		SimpleUniverse1.addBranchGraph(BranchGroup1);
	}
} 
 