QT += widgets
CONFIG += warn_off
INCLUDEPATH += C:\stan-math 
INCLUDEPATH += C:\stan-math\include 
INCLUDEPATH += C:\stan-math\lib\eigen_3.2.9
INCLUDEPATH += C:\stan-math\lib\boost_1.62.0
INCLUDEPATH += C:\stan-math\lib\cvodes_2.9.0\include
HEADERS += QRelation.h QEnergy.h QOptimizer.h QSketch.h QCanvas.h QWindow.h QStanMath.h 
SOURCES += QRelation.cpp QEnergy.cpp QOptimizer.cpp QSketch.cpp QCanvas.cpp QWindow.cpp main.cpp